#!/bin/bash
IFS=$'\n\t'

command=$(zenity  --title "Enter command" --entry --text "Enter the command to run. Filepath will be appended.")

# TODO: Support formats like
# %F - File Paths
# %B - Basenames
output=$(eval "$command" "$1" 2>&1)

notify-send -i info "$command" "$output"
