#!/bin/bash
IFS=$'\n\t'

# Iterate over each passed file
for arg do
    # Uses subliminal: https://github.com/Diaoul/subliminal
    # sudo pip install subliminal
    ~/.local/bin/subliminal -l en -- $arg

    # TODO: Improve Notifications
    # Display, how many subs were downloaded
    # or any errors occurred
    notify-send -i info -a 'Subliminal' 'Subtitle Downloaded' "$arg"
done
