#!/bin/bash

# Extract path to directory
if [ "$NAUTILUS_SCRIPT_CURRENT_URI" == "x-nautilus-desktop:///" ]; then
        DIR=$HOME"/Desktop"
else
        DIR=$(echo "$NAUTILUS_SCRIPT_CURRENT_URI" | sed 's/^file:\/\///' | sed 's/%20/ /g')
fi

# For debugging purposes!
# notify-send -t 1 "Path is" "$DIR"

# Launch!
x-terminal-emulator --maximise --new-tab --working-directory="$DIR"

# Let's focus the terminal we just ran!
pid=$(pgrep -f "x-terminal-emulator")
xdotool windowactivate "$(xdotool search --onlyvisible --pid "$pid")"

exit 0
